### Traefik + step-ca Reverse Proxy Stack
---
name: proxy

services:
  proxy:
    image: "traefik:3.4.1"
    container_name: proxy
    restart: unless-stopped
    environment:  # https://docs.traefik.io/reference/static-configuration/env/
      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: ":80"
      TRAEFIK_API_DASHBOARD: true
      TRAEFIK_PROVIDERS_DOCKER: true
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false
      TRAEFIK_PROVIDERS_DOCKER_DEFAULTRULE: >
        Host(`{{ or (index .Labels "traefik.hostname")
                    (index .Labels "com.docker.compose.service")
                    .Name
              }}.localtest.me`)
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: proxy
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO: web #websecure
      # TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: ":443"
      # TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS: true
      # TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_CERTRESOLVER: stepca
      # TRAEFIK_CERTIFICATESRESOLVERS_STEPCA: true
      # TRAEFIK_CERTIFICATESRESOLVERS_STEPCA_ACME_CASERVER: "https://localhost:9000/acme/acme/directory"
      # TRAEFIK_CERTIFICATESRESOLVERS_STEPCA_ACME_EMAIL: kcollins@inductiveautomation.com
      # TRAEFIK_CERTIFICATESRESOLVERS_STEPCA_ACME_STORAGE: /etc/traefik/acme/acme.json
      # TRAEFIK_CERTIFICATESRESOLVERS_STEPCA_ACME_CERTIFICATESDURATION: 72
      # TRAEFIK_CERTIFICATESRESOLVERS_STEPCA_ACME_TLSCHALLENGE: true
      # TRAEFIK_PROVIDERS_DOCKER_ALLOWEMPTYSERVICES: true
      TRAEFIK_API_DISABLEDASHBOARDAD: true
      TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: false
      TRAEFIK_GLOBAL_CHECKNEWVERSION: false
      TRAEFIK_LOG_LEVEL: DEBUG
      # LEGO_CA_CERTIFICATES: /home/step/certs/root_ca.crt
    # Delay Traefik startup briefly to make sure that step-ca is ready to accept cert renewals immediately
    command: /bin/sh -c "sleep 5 && traefik"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
      # - internal
    labels:
      - "traefik.enable=true"
      - "traefik.hostname=proxy"
      - "traefik.http.routers.proxy.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - step-data:/home/step
      # - traefik-acme:/etc/traefik/acme

  # stepca:
  #   image: "smallstep/step-ca:0.28.3"
  #   container_name: stepca
  #   restart: unless-stopped
  #   environment:
  #     DOCKER_STEPCA_INIT_NAME: Smallstep
  #     DOCKER_STEPCA_INIT_DNS_NAMES: localhost,stepca,stepca.localtest.me
  #     DOCKER_STEPCA_INIT_PROVISIONER_NAME: admin
  #     DOCKER_STEPCA_INIT_ACME: true
  #     DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT: true
  #   # placing in same network namespace as Traefik for TLS-ALPN-01 challenges to be able to
  #   # success against *.localtest.me (i.e. localhost).
  #   network_mode: "service:proxy"
  #   healthcheck:
  #     test: ["CMD", "step", "ca", "health"]
  #     start_interval: 5s
  #     start_period: 10s
  #     interval: 30s
  #     timeout: 5s
  #     retries: 3
  #   volumes:
  #     - type: volume
  #       source: step-data
  #       target: /home/step

networks:
  proxy:
    name: proxy
    # external: true
  # internal:
  #   name: internal
  #   external: true

volumes:
  # step-data:
  traefik-acme:
